#!/usr/bin/env node
/**
 * vendor-fonts.mjs — one-time, ONLINE vendoring of the Google Fonts used by
 * ErgoKit into client/public/fonts/ so the production build needs no network.
 *
 * Run once on a connected machine:  node scripts/vendor-fonts.mjs
 * Then the build (and the deployed app) loads fonts from /fonts/fonts.css only.
 *
 * Families/weights mirror what client/index.html previously requested.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONTS_DIR = path.join(ROOT, 'client', 'public', 'fonts');

// The exact CSS2 request ErgoKit used (Barlow Condensed + DM Sans).
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700' +
  '&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400' +
  '&display=swap';

// A modern desktop Chrome UA makes Google return woff2 (smallest, universally
// supported by the Electron/Chromium runtime).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

function sanitize(url) {
  // Build a stable, readable local filename from the gstatic path.
  const u = new URL(url);
  const parts = u.pathname.split('/').filter(Boolean); // s, <family>, <ver>, <hash>.woff2
  const family = parts[1] ?? 'font';
  const file = parts[parts.length - 1];
  return `${family}-${file}`;
}

async function main() {
  await mkdir(FONTS_DIR, { recursive: true });
  console.log('Fetching font CSS from Google…');
  const cssResp = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!cssResp.ok) throw new Error(`CSS fetch failed: ${cssResp.status}`);
  let css = await cssResp.text();

  // Find every gstatic woff2 URL and download it.
  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
  const unique = [...new Set(urls)];
  console.log(`Found ${unique.length} font files. Downloading…`);

  for (const url of unique) {
    const local = sanitize(url);
    const bin = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`font fetch failed (${bin.status}): ${url}`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(path.join(FONTS_DIR, local), buf);
    // Rewrite every reference to this URL to a root-absolute local path.
    css = css.split(url).join(`/fonts/${local}`);
    console.log(`  ✓ ${local} (${(buf.length / 1024).toFixed(1)} KB)`);
  }

  // Any remaining remote refs would defeat the purpose — fail loudly.
  if (/https?:\/\//.test(css)) {
    throw new Error('CSS still contains remote URLs after rewrite — aborting.');
  }

  const banner =
    '/* ErgoKit self-hosted fonts — generated by scripts/vendor-fonts.mjs.\n' +
    '   No network references. Safe for air-gapped / ITAR deployment. */\n';
  await writeFile(path.join(FONTS_DIR, 'fonts.css'), banner + css, 'utf-8');
  console.log(`\nWrote ${path.relative(ROOT, path.join(FONTS_DIR, 'fonts.css'))}`);
  console.log('Done. Ensure index.html links /fonts/fonts.css (no fonts.googleapis.com).');
}

main().catch((e) => {
  console.error('vendor-fonts failed:', e.message);
  process.exit(1);
});
